name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: cd mylib/ ;
           make all ;
           cd .. ;
    - name: make clean
      run: make clean
    - name: make build
      run: export LD_LIBRARY_PATH=/home/runner/work/Programming/Programming/mylib:$LD_LIBRARY_PATH ; 
           make all_github ;
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
